version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: mysql-maichaun
    networks:
      - kelner
    ports: 
      - '3307:33060'
    environment:
      MYSQL_ROOT_PASSWORD: password

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-maichaun
    restart: always
    ports:
      - '8080:80'
    networks:
      - kelner
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    command: yarn dev
    depends_on:
      - db
    container_name: server-maichaun
    networks:
      - kelner
    volumes: 
      - .:/app
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_ROOT_HOST: mysql-maichaun

  schedule:
    image: kelner-scheduling
    restart: always
    ports:
      - "7777:7777"
    command: yarn dev
    networks:
      - kelner
    container_name: kelner-scheduling
    environment: 
      SCHEDULE_CRON: 44 * * * *
      HOST: http://api:3000
volumes:
  db_data:
networks:
  kelner: